apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nirn-proxy
  namespace: nirn-system
spec:
  serviceName: "nirn-discovery"
  replicas: 3
  selector:
    matchLabels:
      app: nirn-proxy
  template:
    metadata:
      labels:
        app: nirn-proxy
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchLabels:
                  app: nirn-proxy
              topologyKey: "kubernetes.io/hostname"
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            preference:
              matchExpressions:
              - key: node-role.kubernetes.io/master
                operator: DoesNotExist
          - weight: 100
            preference:
              matchExpressions:
              - key: node-role.kubernetes.io/control-plane
                operator: DoesNotExist
      containers:
      - name: proxy
        image: ghcr.io/davfsa/nirn-proxy
        env:
        - name: CLUSTER_DNS
          value: "nirn-discovery.nirn-system.svc.cluster.local"
        - name: METRICS_PORT
          value: "9000"
        - name: ENABLE_METRICS
          value: "true"
        ports:
        - name: http
          containerPort: 8080
        - name: gossip
          containerPort: 7946
        - name: metrics
          containerPort: 9000
        livenessProbe:
          httpGet:
            path: /nirn/healthz
            port: http
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /nirn/healthz
            port: http
          initialDelaySeconds: 5
          periodSeconds: 5
