apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nirn-proxy
  namespace: nirn-system
spec:
  serviceName: "nirn-discovery"
  replicas: 3
  selector:
    matchLabels:
      app: nirn-proxy
  template:
    metadata:
      labels:
        app: nirn-proxy
    spec:
      containers:
      - name: proxy
        image: ghcr.io/davfsa/nirn-proxy
        env:
        - name: CLUSTER_DNS
          value: "nirn-discovery.nirn-system.svc.cluster.local"
        - name: METRICS_PORT
          value: "9000"
        - name: ENABLE_METRICS
          value: "true"
        ports:
        - name: http
          containerPort: 8080
        - name: gossip
          containerPort: 7946
        - name: metrics
          containerPort: 9000
